name: Deploy to GitHub Pages

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to commit changes (e.g., to bookmarks.txt)
      pages: write   # Needed to deploy to GitHub Pages
      id-token: write # Needed to request OIDC token for actions/deploy-pages
    environment:
      name: github-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Example step: Append to bookmarks.txt (adjust as needed)
      - name: Append Bookmark
        run: |
          echo "{\"title\": \"Test $(date +%Y-%m-%d)\", \"url\": \"https://example.com\", \"category\": \"Test\", \"image\": \"${defaultImage}\"}" >> bookmarks.txt
        env:
          defaultImage: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='200' height='150' viewBox='0 0 200 150'%3E%3Crect width='100%25' height='100%25' fill='%23cccccc'/%3E%3Ctext x='50%25' y='50%25' font-family='Arial, sans-serif' font-size='20' fill='%23000000' text-anchor='middle' dominant-baseline='middle'%3EImage Not Available%3C/text%3E%3C/svg%3E"

      - name: Commit changes
        run: |
          git config --global user.name 'nitindinnu'
          git config --global user.email 'nitin2239@protonmail.com'
          git add bookmarks.txt
          git commit -m "Update bookmarks.txt on $(date +%Y-%m-%dT%H:%M:%S%Z)" || echo "No changes to commit"
          git push

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Uploads the entire repository root

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
          artifact_name: github-pages
          preview: false
        env:
          GITHUB_PAGES: true
