name: Daily Bookmark Update

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC daily
  workflow_dispatch: # Allows manual triggering

jobs:
  update-bookmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Append New Bookmark
        run: |
          node -e "
            const fs = require('fs');
            let html = fs.readFileSync('index.html', 'utf8');
            const newBookmark = { 
              title: 'Daily Update ${new Date().toISOString().split('T')[0]}', 
              url: 'https://example.com/daily-${new Date().toISOString().split('T')[0]}', 
              category: 'Daily', 
              image: '${defaultImage}' 
            };
            const defaultBookmarksIndex = html.indexOf('const defaultBookmarks = [');
            const arrayStart = html.indexOf('[', defaultBookmarksIndex);
            const arrayEnd = html.indexOf('];', arrayStart) + 1;
            const existingArray = html.slice(arrayStart, arrayEnd);
            const updatedArray = existingArray.slice(0, -1) + ',' + JSON.stringify(newBookmark) + existingArray.slice(-1);
            const updatedHtml = html.slice(0, arrayStart) + updatedArray + html.slice(arrayEnd);
            fs.writeFileSync('index.html', updatedHtml);
          "

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add index.html
          git commit -m "Daily update: added bookmark for $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push
