name: Daily Update

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC daily
  workflow_dispatch: # Allows manual triggering

jobs:
  update-bookmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Update Bookmarks
        run: |
          # Example: Append a new bookmark to localStorage defaults (simulated)
          node -e "
            const fs = require('fs');
            let html = fs.readFileSync('index.html', 'utf8');
            const newBookmark = { title: 'Daily Update ${new Date().toISOString().split('T')[0]}', url: 'https://example.com', category: 'General', image: '' };
            const scriptTag = '<script>';
            const insertIndex = html.indexOf(scriptTag) + scriptTag.length;
            const updatedHtml = html.slice(0, insertIndex) + \`
              const defaultBookmarks = JSON.parse(localStorage.getItem('bookmarks')) || [];
              if (!defaultBookmarks.some(b => b.title === '${newBookmark.title}')) {
                defaultBookmarks.push(${JSON.stringify(newBookmark)});
                localStorage.setItem('bookmarks', JSON.stringify(defaultBookmarks));
              }
            \` + html.slice(insertIndex);
            fs.writeFileSync('index.html', updatedHtml);
          "

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add index.html
          git commit -m "Daily update: added new bookmark for $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push
